html:
  - bg
  - fg
  - white
  - gray
  - black
  - red
  - magenta
  - purple
  - blue
  - cyan
  - green
  - yellow
  - orange

wezterm:
  fg: fg
  bg: bg
  cursor_fg: cursor_fg
  cursor_bg: cursor_bg
  cursor_border: cursor_bg
  selection_bg: selection_bg
  selection_fg: selection_fg
  black: dark_gray
  red: red
  green: green
  yellow: yellow
  blue: blue
  purple: purple
  cyan: cyan
  white: light_gray
  bright_black: gray
  bright_red: light_red
  bright_green: light_green
  bright_yellow: light_yellow
  bright_blue: light_blue
  bright_purple: magenta
  bright_cyan: light_cyan
  bright_white: white

k9s:
  fg: fg
  bg: bg
  black: black
  blue: blue
  green: green
  gray: gray
  orange: orange
  purple: magenta
  red: red
  yellow: yellow
  brightYellow: light_yellow

lualine:
  normal: blue
  insert: green
  visual: purple
  replace: red
  command: orange
  fg: fg
  bg: bg
  bg_alt: black

Normal: 'fg bg'

groups:
  cursor:
    Cursor: 'cursor_fg cursor_bg'
    CursorLine: '- cursor_line'

  types:
    SpecialChar: 'fg'
    Operator: 'fg'

    String: 'green'

    Character: 'orange'
    Special: 'orange'

    Number: 'cyan'
    Float: 'cyan'

    Variable: 'light_blue'
    Identifier: 'light_blue'

    Function: 'yellow'

    Constant: 'blue'
    Boolean: 'blue'
    Type: 'blue'
    StorageClass: 'blue'
    Structure: 'blue'
    Typedef: 'blue'
    Conditional: 'blue'
    Tag: 'blue'

    Keyword: 'purple'
    Statement: 'purple'
    Repeat: 'purple'
    Label: 'purple'
    Exception: 'purple'
    Include: 'purple'
    PreProc: 'purple'
    Define: 'purple'
    Macro: 'purple'
    PreCondit: 'purple'


  diff:
    DiffAdd: 'bg_light sign_add'
    DiffChange: 'bg_light sign_change u'
    DiffDelete: 'bg_light sign_delete'

  highlights:
    MatchWord: '- - u'
    MatchParen: 'hint bg u'
    MatchWordCur: '- - u'
    MatchParenCur: '- - u'
    SignColumn: '- bg'
    MsgArea: 'fg bg'
    ModeMsg: 'fg bg'
    MsgSeparator: 'fg bg'
    SpellBad: 'error - u'
    SpellCap: 'yellow - u'
    SpellLocal: 'green - u'
    SpellRare: 'purple - u'
    NormalNC: 'fg bg'
    Pmenu: 'light_gray'
    PmenuSel: 'bg_light blue'
    PmenuSbar: '- bg_dark'
    PmenuThumb: '- gray'
    WildMenu: 'bg_light blue'
    Comment: 'comment - i'
    Folded: 'accent bg_light'
    FoldColumn: 'accent bg_light'
    LineNr: 'gray -'
    FloatBorder: 'gray bg_light'
    Whitespace: 'bg -'
    VertSplit: 'fg bg'
    ColorColumn: '- bg_dark'
    NormalFloat: '- bg_dark'
    Visual: '- selection_bg'
    VisualNOS: '- bg_light'
    WarningMsg: 'error bg'
    QuickFixLine: '- black'
    Conceal: 'accent'
    Directory: 'blue'
    SpecialKey: 'blue - b'
    Title: 'blue - b'
    ErrorMsg: 'error bg b'
    Search: 'light_gray search_blue'
    IncSearch: 'light_gray search_blue'
    Substitute: 'dark_gray search_orange'
    MoreMsg: 'orange'
    Question: 'orange'
    EndOfBuffer: 'bg'
    NonText: 'bg'
    Debug: 'red'
    Delimiter: 'gray -'
    SpecialComment: 'comment'
    Underlined: '- - u'
    Bold: '- - b'
    Italic: '- - i'
    Ignore: 'cyan bg b'
    Todo: 'purple bg b'
    Error: 'error bg b'
    TabLine: 'light_gray bg_light'
    TabLineSel: 'white bg_light'
    TabLineFill: 'white bg_light'

  treesitter:
    TSComment: 'comment'
    TSAnnotation: 'yellow'
    TSAttribute: 'orange'
    TSConstructor: 'orange'
    TSType: 'orange'
    TSTypeBuiltin: 'blue'
    TSConditional: 'blue'
    TSException: 'purple'
    TSInclude: 'purple'
    TSKeywordReturn: 'purple'
    TSKeyword: 'blue'
    TSKeywordFunction: 'blue'
    TSLabel: 'light_blue'
    TSNamespace: 'orange'
    TSRepeat: 'purple'
    TSConstant: 'yellow'
    TSConstBuiltin: 'blue'
    TSFloat: 'green'
    TSNumber: 'green'
    TSBoolean: 'blue'
    TSCharacter: 'orange'
    TSError: 'error'
    TSFunction: 'yellow'
    TSFuncBuiltin: 'yellow'
    TSMethod: 'yellow'
    TSConstMacro: 'orange'
    TSFuncMacro: 'yellow'
    TSVariable: 'light_blue'
    TSVariableBuiltin: 'light_blue'
    TSProperty: 'light_blue'
    TSOperator: 'fg'
    TSField: 'light_blue'
    TSParameter: 'light_blue'
    TSParameterReference: 'light_blue'
    TSSymbol: 'light_blue'
    TSText: 'fg'
    TSPunctDelimiter: 'fg -'
    TSTagDelimiter: 'gray'
    TSPunctBracket: 'fg -'
    TSPunctSpecial: 'fg'
    TSString: 'cyan'
    TSStringRegex: 'cyan'
    TSStringEscape: 'green'
    TSTag: 'blue'
    TSEmphasis: '- - i'
    TSUnderline: '- - u'
    TSTitle: 'blue - b'
    TSLiteral: 'orange'
    TSURI: 'orange - u'
    TSKeywordOperator: 'blue'
    TSStructure: 'light_blue'
    TSStrong: 'orange'
    TSQueryLinterError: 'warning'
    TSInstalled: 'green black'
    TSMissing: 'error black'

  git:
    SignAdd: 'sign_add'
    SignChange: 'sign_change'
    SignDelete: 'sign_delete'
    GitSignsAdd: 'sign_add'
    GitSignsChange: 'sign_change'
    GitSignsDelete: 'sign_delete'

    DiffViewNormal: 'gray bg_light'
    DiffviewStatusAdded: 'sign_add'
    DiffviewStatusModified: 'sign_change'
    DiffviewStatusRenamed: 'sign_change'
    DiffviewStatusDeleted: 'sign_delete'
    DiffviewFilePanelInsertion: 'sign_add'
    DiffviewFilePanelDeletion: 'sign_delete'
    DiffviewVertSplit: '- bg'

    diffAdded: 'sign_add'
    diffRemoved: 'sign_delete'
    diffFileId: 'blue - br'
    diffFile: comment
    diffNewFile: 'green'
    diffOldFile: 'red'

  lualine:
    LuaLineDiffAdd: 'sign_add'
    LuaLineDiffChange: 'sign_change'
    LuaLineDiffDelete: 'sign_delete'

  lsp:
    LspCodeLens: 'gray'
    LspInlayHint: 'gray'
    LspDiagnosticsDefaultError: 'error'
    LspDiagnosticsDefaultWarning: 'warning'
    LspDiagnosticsDefaultInformation: 'info'
    LspDiagnosticsDefaultHint: 'hint'
    LspDiagnosticsVirtualTextError: 'error'
    LspDiagnosticsVirtualTextWarning: 'warning'
    LspDiagnosticsVirtualTextInformation: 'info'
    LspDiagnosticsVirtualTextHint: 'hint'
    LspDiagnosticsFloatingError: 'error'
    LspDiagnosticsFloatingWarning: 'warning'
    LspDiagnosticsFloatingInformation: 'info'
    LspDiagnosticsFloatingHint: 'hint'
    LspDiagnosticsSignError: 'error'
    LspDiagnosticsSignWarning: 'warning'
    LspDiagnosticsSignInformation: 'info'
    LspDiagnosticsSignHint: 'hint'
    LspDiagnosticsError: 'error'
    LspDiagnosticsWarning: 'warning'
    LspDiagnosticsInformation: 'info'
    LspDiagnosticsHint: 'hint'
    LspDiagnosticsUnderlineError: '- - u'
    LspDiagnosticsUnderlineWarning: '- - u'
    LspDiagnosticsUnderlineInformation: '- - u'
    LspDiagnosticsUnderlineHint: '- - u'

    QuickScopePrimary: 'magenta - u'
    QuickScopeSecondary: 'hint - u'

  telescope:
    TelescopeSelection: 'hint'
    TelescopeMatching: 'info - b'

  nvim_tree:
    NvimTreeFolderIcon: 'blue'
    NvimTreeIndentMarker: 'gray'
    NvimTreeNormal: 'light_gray bg_light'
    NvimTreeVertSplit: 'bg_light bg_light'
    NvimTreeFolderName: 'blue'
    NvimTreeOpenedFolderName: 'cyan - i'
    NvimTreeImageFile: 'purple'
    NvimTreeSpecialFile: 'orange'
    NvimTreeGitStaged: 'sign_add'
    NvimTreeGitNew: 'sign_add'
    NvimTreeGitDirty: 'sign_add'
    NvimTreeGitDeleted: 'sign_delete'
    NvimTreeGitMerge: 'sign_change'
    NvimTreeGitRenamed: 'sign_change'
    NvimTreeSymlink: 'cyan'
    NvimTreeRootFolder: 'fg - b'
    NvimTreeExecFile: 'green'

  alpha:
    DashboardHeader: 'light_blue'
    DashboardCenter: 'purple'
    DashboardFooter: 'cyan'

  illuminate:
    IlluminatedWordText: '- highlight_alt_bg'
    IlluminatedWordRead: '- highlight_alt_bg'
    IlluminatedWordWrite: '- highlight_alt_bg'
