package colorschemes

var BaseHighlights = &Highlights{
	Terminal: &TerminalHL{
		Foreground:   "fg",
		Background:   "bg",
		CursorFG:     "cursor_fg",
		CursorBG:     "cursor_bg",
		SelectionBG:  "search",
		SelectionFG:  "fg",
		Black:        "dark_gray",
		Red:          "red",
		Green:        "green",
		Yellow:       "yellow",
		Blue:         "blue",
		Purple:       "purple",
		Cyan:         "cyan",
		White:        "light_gray",
		BrightBlack:  "gray",
		BrightRed:    "light_red",
		BrightGreen:  "light_green",
		BrightYellow: "light_yellow",
		BrightBlue:   "light_blue",
		BrightPurple: "magenta",
		BrightCyan:   "light_cyan",
		BrightWhite:  "white",
	},
	K9s: &K9sHL{
		FG:           "fg",
		BG:           "bg",
		Black:        "dark_gray",
		Blue:         "blue",
		Green:        "green",
		Gray:         "gray",
		Orange:       "orange",
		Purple:       "magenta",
		Red:          "red",
		Yellow:       "yellow",
		BrightYellow: "light_yellow",
	},
	Lualine: &LualineHL{
		Normal:  "blue",
		Insert:  "green",
		Visual:  "purple",
		Replace: "red",
		Command: "orange",
		Fg:      "fg",
		Bg:      "bg",
		BgAlt:   "bg_dark",
	},
	Normal: Highlight{FG: "fg", BG: "bg"},
	Groups: map[string]map[string]Highlight{
		"cursor": {
			"Cursor":     {FG: "cursor_fg", BG: "cursor_bg"},
			"CursorLine": {BG: "cursor_line"},
		},
		"types": {
			"SpecialChar": {FG: "fg"},
			"Operator":    {FG: "fg"},
			"@variable":   {FG: "fg"},

			"String": {FG: "green"},

			"Character": {FG: "orange"},
			"Special":   {FG: "orange"},

			"Number": {FG: "cyan"},
			"Float":  {FG: "cyan"},

			"Function": {FG: "yellow"},

			"Constant":     {FG: "blue"},
			"Boolean":      {FG: "blue"},
			"Type":         {FG: "blue"},
			"StorageClass": {FG: "blue"},
			"Structure":    {FG: "blue"},
			"Typedef":      {FG: "blue"},
			"Conditional":  {FG: "blue"},
			"Tag":          {FG: "blue"},

			"@variable.member": {FG: "light_blue"},
			"Variable":         {FG: "light_blue"},
			"Identifier":       {FG: "light_blue"},

			"Keyword":   {FG: "purple"},
			"Statement": {FG: "purple"},
			"Repeat":    {FG: "purple"},
			"Label":     {FG: "purple"},
			"Exception": {FG: "purple"},
			"Include":   {FG: "purple"},

			"PreProc":   {FG: "magenta"},
			"Define":    {FG: "magenta"},
			"PreCondit": {FG: "magenta"},
			"Macro":     {FG: "magenta"},
		},
		"diff": {
			"Added":   {FG: "sign_add"},
			"Changed": {FG: "sign_change"},
			"Removed": {FG: "sign_delete"},

			"DiffAdd":    {BG: "sign_add_bg"},
			"DiffChange": {BG: "sign_change_bg"},
			"DiffDelete": {BG: "sign_delete_bg"},
			"DiffText":   {BG: "sign_diff_bg"},

			"GitSignsAdd":          {Link: "Added"},
			"GitSignsChange":       {Link: "Changed"},
			"GitSignsDelete":       {Link: "Removed"},
			"GitSignsStagedAdd":    {FG: "sign_staged_add"},
			"GitSignsStagedChange": {FG: "sign_staged_change"},
			"GitSignsStagedDelete": {FG: "sign_staged_delete"},
		},
		"highlights": {
			"MatchWord":      {Underline: true},
			"MatchParen":     {FG: "hint", BG: "bg", Underline: true},
			"MatchWordCur":   {Underline: true},
			"MatchParenCur":  {Underline: true},
			"SignColumn":     {BG: "bg"},
			"MsgArea":        {FG: "fg", BG: "bg"},
			"ModeMsg":        {FG: "fg", BG: "bg"},
			"MsgSeparator":   {FG: "fg", BG: "bg"},
			"SpellBad":       {FG: "error", Underline: true},
			"SpellCap":       {FG: "yellow", Underline: true},
			"SpellLocal":     {FG: "green", Underline: true},
			"SpellRare":      {FG: "purple", Underline: true},
			"NormalNC":       {FG: "fg", BG: "bg"},
			"Pmenu":          {FG: "light_gray"},
			"PmenuSel":       {FG: "bg_light", BG: "blue"},
			"PmenuSbar":      {BG: "bg_dark"},
			"PmenuThumb":     {BG: "gray"},
			"WildMenu":       {FG: "bg_light", BG: "blue"},
			"Comment":        {FG: "comment", Italic: true},
			"Folded":         {FG: "accent", BG: "bg_light"},
			"FoldColumn":     {FG: "accent", BG: "bg_light"},
			"LineNr":         {FG: "gray"},
			"FloatBorder":    {FG: "gray"},
			"Whitespace":     {FG: "bg"},
			"VertSplit":      {FG: "fg", BG: "bg"},
			"ColorColumn":    {BG: "bg_dark"},
			"NormalFloat":    {BG: "bg_dark"},
			"Visual":         {BG: "search"},
			"VisualNOS":      {BG: "bg_light"},
			"WarningMsg":     {FG: "error", BG: "bg"},
			"QuickFixLine":   {BG: "bg_dark"},
			"Conceal":        {FG: "accent"},
			"Directory":      {FG: "blue"},
			"SpecialKey":     {FG: "blue", Bold: true},
			"Title":          {FG: "blue", Bold: true},
			"ErrorMsg":       {FG: "error", BG: "bg", Bold: true},
			"Search":         {BG: "search"},
			"IncSearch":      {BG: "search"},
			"Substitute":     {BG: "replace"},
			"MoreMsg":        {FG: "orange"},
			"Question":       {FG: "orange"},
			"EndOfBuffer":    {FG: "bg"},
			"NonText":        {FG: "bg"},
			"Debug":          {FG: "red"},
			"Delimiter":      {FG: "gray"},
			"SpecialComment": {FG: "comment"},
			"Underlined":     {Underline: true},
			"Bold":           {Bold: true},
			"Italic":         {Italic: true},
			"Ignore":         {FG: "cyan", BG: "bg", Bold: true},
			"Todo":           {FG: "purple", BG: "bg", Bold: true},
			"Error":          {FG: "error", BG: "bg", Bold: true},
			"TabLine":        {FG: "light_gray", BG: "bg_light"},
			"TabLineSel":     {FG: "white", BG: "bg_light"},
			"TabLineFill":    {FG: "white", BG: "bg_light"},
		},
		"treesitter": {
			"TSInstalled": {Link: "Added"},
			"TSMissing":   {Link: "Removed"},
		},
		"lsp": {
			"LspCodeLens":                          {FG: "gray"},
			"LspInlayHint":                         {FG: "gray"},
			"LspDiagnosticsDefaultError":           {FG: "error"},
			"LspDiagnosticsDefaultWarning":         {FG: "warning"},
			"LspDiagnosticsDefaultInformation":     {FG: "info"},
			"LspDiagnosticsDefaultHint":            {FG: "hint"},
			"LspDiagnosticsVirtualTextError":       {FG: "error"},
			"LspDiagnosticsVirtualTextWarning":     {FG: "warning"},
			"LspDiagnosticsVirtualTextInformation": {FG: "info"},
			"LspDiagnosticsVirtualTextHint":        {FG: "hint"},
			"LspDiagnosticsFloatingError":          {FG: "error"},
			"LspDiagnosticsFloatingWarning":        {FG: "warning"},
			"LspDiagnosticsFloatingInformation":    {FG: "info"},
			"LspDiagnosticsFloatingHint":           {FG: "hint"},
			"LspDiagnosticsSignError":              {FG: "error"},
			"LspDiagnosticsSignWarning":            {FG: "warning"},
			"LspDiagnosticsSignInformation":        {FG: "info"},
			"LspDiagnosticsSignHint":               {FG: "hint"},
			"LspDiagnosticsError":                  {FG: "error"},
			"LspDiagnosticsWarning":                {FG: "warning"},
			"LspDiagnosticsInformation":            {FG: "info"},
			"LspDiagnosticsHint":                   {FG: "hint"},
			"LspDiagnosticsUnderlineError":         {Underline: true},
			"LspDiagnosticsUnderlineWarning":       {Underline: true},
			"LspDiagnosticsUnderlineInformation":   {Underline: true},
			"LspDiagnosticsUnderlineHint":          {Underline: true},
			"QuickScopePrimary":                    {FG: "magenta", Underline: true},
			"QuickScopeSecondary":                  {FG: "hint", Underline: true},
		},
		"telescope": {
			"TelescopeSelection": {FG: "hint"},
			"TelescopeMatching":  {FG: "info", Bold: true},
		},
		"nvim_tree": {
			"NvimTreeGitFileDirtyHL":   {Link: "DiffChange"},
			"NvimTreeGitFileDirtyIcon": {Link: "NvimTreeGitFileDirtyHL"},

			"NvimTreeGitFileStagedHL":   {Link: "DiffAdd"},
			"NvimTreeGitFileStagedIcon": {Link: "NvimTreeGitFileStagedIcon"},

			"NvimTreeGitFileNewHL":   {Link: "DiffText"},
			"NvimTreeGitFileNewIcon": {Link: "NvimTreeGitFileNewHL"},

			"NvimTreeFolderIcon":       {FG: "blue"},
			"NvimTreeIndentMarker":     {FG: "gray"},
			"NvimTreeNormal":           {FG: "light_gray", BG: "bg_light"},
			"NvimTreeVertSplit":        {FG: "bg_light", BG: "bg_light"},
			"NvimTreeFolderName":       {FG: "blue"},
			"NvimTreeOpenedFolderName": {FG: "cyan", Italic: true},
			"NvimTreeOpenedFolderIcon": {Link: "NvimTreeOpenedFolderName"},
			"NvimTreeImageFile":        {FG: "purple"},
			"NvimTreeSpecialFile":      {FG: "orange"},
			"NvimTreeSymlink":          {FG: "cyan"},
			"NvimTreeRootFolder":       {FG: "fg", Bold: true},
			"NvimTreeExecFile":         {FG: "green"},
			// "NvimTreeGitStaged":        {FG: "sign_add"},
			// "NvimTreeGitNew":           {FG: "sign_add"},
			// "NvimTreeGitDirty":         {FG: "sign_diff"},
			// "NvimTreeGitDeleted":       {FG: "sign_delete"},
			// "NvimTreeGitMerge":         {FG: "sign_change"},
			// "NvimTreeGitRenamed":       {FG: "sign_change"},
		},
		"alpha": {
			"DashboardHeader":            {FG: "light_blue"},
			"DashboardCenter":            {FG: "purple"},
			"DashboardFooter":            {FG: "cyan"},
			"DashboardButtonText":        {FG: "light_gray"},
			"DashboardButtonTextAlt":     {FG: "gray"},
			"DashboardButtonShortcut":    {FG: "magenta"},
			"DashboardButtonShortcutAlt": {FG: "purple"},
		},
		"illuminate": {
			"IlluminatedWordText":  {BG: "highlight_alt_bg"},
			"IlluminatedWordRead":  {BG: "highlight_alt_bg"},
			"IlluminatedWordWrite": {BG: "highlight_alt_bg"},
		},
	},
}
