local M = {}

local c = require("system76.colors")
local hl = vim.api.nvim_set_hl

function M.setup()
	-- alpha
	hl(0, "DashboardCenter", { fg = c.purple })
	hl(0, "DashboardFooter", { fg = c.cyan })
	hl(0, "DashboardHeader", { fg = c.light_blue })

	-- bufferline
	hl(0, "BufferCurrent", { fg = c.fg, bg = bg })
	hl(0, "BufferCurrentIndex", { fg = c.fg, bg = bg })
	hl(0, "BufferCurrentMod", { fg = c.info_yellow, bg = bg })
	hl(0, "BufferCurrentSign", { fg = c.hint_blue, bg = bg })
	hl(0, "BufferCurrentTarget", { fg = c.red, bg = bg, bold = true })
	hl(0, "BufferInactive", { fg = c.gray, bg = alt_bg })
	hl(0, "BufferInactiveIndex", { fg = c.gray, bg = alt_bg })
	hl(0, "BufferInactiveMod", { fg = c.info_yellow, bg = alt_bg })
	hl(0, "BufferInactiveSign", { fg = c.gray, bg = alt_bg })
	hl(0, "BufferInactiveTarget", { fg = c.red, bg = alt_bg, bold = true })
	hl(0, "BufferVisible", { fg = c.fg, bg = bg })
	hl(0, "BufferVisibleIndex", { fg = c.fg, bg = bg })
	hl(0, "BufferVisibleMod", { fg = c.info_yellow, bg = bg })
	hl(0, "BufferVisibleSign", { fg = c.gray, bg = bg })
	hl(0, "BufferVisibleTarget", { fg = c.red, bg = bg, bold = true })
	hl(0, "IndentBlanklineChar", { fg = c.dark_gray })
	hl(0, "IndentBlanklineContextChar", { fg = c.context })
	hl(0, "IndentBlanklineSpaceChar", { fg = c.cyan_test })
	hl(0, "IndentBlanklineSpaceCharBlankline", { fg = c.info_yellow })
	hl(0, "StatusLine", { fg = c.alt_bg })
	hl(0, "StatusLineNC", { fg = c.alt_bg })
	hl(0, "StatusLineSeparator", { fg = c.alt_bg })
	hl(0, "StatusLineTerm", { fg = c.alt_bg })
	hl(0, "StatusLineTermNC", { fg = c.alt_bg })

	-- git
	hl(0, "DiffViewNormal", { fg = c.gray, bg = alt_bg })
	hl(0, "DiffviewFilePanelDeletion", { fg = c.sign_delete })
	hl(0, "DiffviewFilePanelInsertion", { fg = c.sign_add })
	hl(0, "DiffviewStatusAdded", { fg = c.sign_add })
	hl(0, "DiffviewStatusDeleted", { fg = c.sign_delete })
	hl(0, "DiffviewStatusModified", { fg = c.sign_change })
	hl(0, "DiffviewStatusRenamed", { fg = c.sign_change })
	hl(0, "DiffviewVertSplit", { fg = "fg", bg = bg })
	hl(0, "GitSignsAdd", { fg = c.sign_add })
	hl(0, "GitSignsChange", { fg = c.sign_change })
	hl(0, "GitSignsDelete", { fg = c.sign_delete })
	hl(0, "SignAdd", { fg = c.sign_add })
	hl(0, "SignChange", { fg = c.sign_change })
	hl(0, "SignDelete", { fg = c.sign_delete })
	hl(0, "diffAdded", { fg = c.sign_add })
	hl(0, "diffFile", { fg = c.alt_bg })
	hl(0, "diffFileId", { fg = c.blue, bg = "bg" })
	hl(0, "diffNewFile", { fg = c.green })
	hl(0, "diffOldFile", { fg = c.red })
	hl(0, "diffRemoved", { fg = c.sign_delete })

	-- highlights
	hl(0, "Bold", { fg = "fg", bg = "bg", bold = true })
	hl(0, "Boolean", { fg = c.blue })
	hl(0, "Character", { fg = c.orange })
	hl(0, "ColorColumn", { fg = "fg", bg = dark })
	hl(0, "Comment", { fg = c.comment, bg = "bg", italic = true })
	hl(0, "Conceal", { fg = c.accent })
	hl(0, "Conditional", { fg = c.blue })
	hl(0, "Constant", { fg = c.blue })
	hl(0, "Cursor", { fg = c.cursor_fg, bg = cursor_bg })
	hl(0, "CursorColumn", { fg = "fg", bg = dark })
	hl(0, "CursorIM", { fg = c.cursor_fg, bg = cursor_bg })
	hl(0, "CursorLine", { fg = "fg", bg = dark })
	hl(0, "CursorLineNr", { fg = c.light_gray, bg = "bg", bold = true })
	hl(0, "Debug", { fg = c.red })
	hl(0, "Define", { fg = c.purple })
	hl(0, "Delimiter", { fg = c.gray, bg = "bg" })
	hl(0, "DiffAdd", { fg = c.alt_bg, bg = sign_add })
	hl(0, "DiffChange", { fg = c.alt_bg, bg = sign_change, underline = true })
	hl(0, "DiffDelete", { fg = c.alt_bg, bg = sign_delete })
	hl(0, "Directory", { fg = c.blue })
	hl(0, "EndOfBuffer", { fg = c.bg })
	hl(0, "Error", { fg = c.error_red, bg = bg, bold = true })
	hl(0, "ErrorMsg", { fg = c.error_red, bg = bg, bold = true })
	hl(0, "Exception", { fg = c.purple })
	hl(0, "Float", { fg = c.green })
	hl(0, "FloatBorder", { fg = c.gray, bg = alt_bg })
	hl(0, "FoldColumn", { fg = c.accent, bg = alt_bg })
	hl(0, "Folded", { fg = c.accent, bg = alt_bg })
	hl(0, "Function", { fg = c.yellow })
	hl(0, "Identifier", { fg = c.light_blue })
	hl(0, "Ignore", { fg = c.cyan, bg = bg, bold = true })
	hl(0, "IncSearch", { fg = c.light_gray, bg = search_blue })
	hl(0, "Include", { fg = c.purple })
	hl(0, "Italic", { fg = "fg", bg = "bg", italic = true })
	hl(0, "Keyword", { fg = c.purple })
	hl(0, "Label", { fg = c.purple })
	hl(0, "LineNr", { fg = c.gray, bg = "bg" })
	hl(0, "Macro", { fg = c.purple })
	hl(0, "MatchParen", { fg = c.hint_blue, bg = bg, underline = true })
	hl(0, "MatchParenCur", { fg = "fg", bg = "bg", underline = true })
	hl(0, "MatchWord", { fg = "fg", bg = "bg", underline = true })
	hl(0, "MatchWordCur", { fg = "fg", bg = "bg", underline = true })
	hl(0, "ModeMsg", { fg = c.fg, bg = bg })
	hl(0, "MoreMsg", { fg = c.orange })
	hl(0, "MsgArea", { fg = c.fg, bg = bg })
	hl(0, "MsgSeparator", { fg = c.fg, bg = bg })
	hl(0, "NonText", { fg = c.bg })
	hl(0, "Normal", { fg = c.fg, bg = bg })
	hl(0, "NormalFloat", { fg = "fg", bg = dark })
	hl(0, "NormalNC", { fg = c.fg, bg = bg })
	hl(0, "Number", { fg = c.green })
	hl(0, "Operator", { fg = c.fg })
	hl(0, "Pmenu", { fg = c.light_gray, bg = popup_back })
	hl(0, "PmenuSbar", { fg = "fg", bg = alt_bg })
	hl(0, "PmenuSel", { fg = c.alt_bg, bg = blue })
	hl(0, "PmenuThumb", { fg = "fg", bg = gray })
	hl(0, "PreCondit", { fg = c.purple })
	hl(0, "PreProc", { fg = c.purple })
	hl(0, "Question", { fg = c.orange })
	hl(0, "QuickFixLine", { fg = "fg", bg = accent })
	hl(0, "Repeat", { fg = c.purple })
	hl(0, "Search", { fg = c.light_gray, bg = search_blue })
	hl(0, "SignColumn", { fg = "fg", bg = bg })
	hl(0, "Special", { fg = c.orange })
	hl(0, "SpecialChar", { fg = c.white })
	hl(0, "SpecialComment", { fg = c.comment })
	hl(0, "SpecialKey", { fg = c.blue, bg = "bg", bold = true })
	hl(0, "SpellBad", { fg = c.error_red, bg = "bg", underline = true })
	hl(0, "SpellCap", { fg = c.yellow, bg = "bg", underline = true })
	hl(0, "SpellLocal", { fg = c.green, bg = "bg", underline = true })
	hl(0, "SpellRare", { fg = c.purple, bg = "bg", underline = true })
	hl(0, "Statement", { fg = c.purple })
	hl(0, "StorageClass", { fg = c.blue })
	hl(0, "String", { fg = c.cyan })
	hl(0, "Structure", { fg = c.blue })
	hl(0, "Substitute", { fg = c.light_gray, bg = search_orange })
	hl(0, "TabLine", { fg = c.light_gray, bg = alt_bg })
	hl(0, "TabLineFill", { fg = c.white, bg = alt_bg })
	hl(0, "TabLineSel", { fg = c.white, bg = alt_bg })
	hl(0, "Tag", { fg = c.blue })
	hl(0, "TermCursor", { fg = c.cursor_fg, bg = cursor_bg })
	hl(0, "TermCursorNC", { fg = c.cursor_fg, bg = cursor_bg })
	hl(0, "Title", { fg = c.blue, bg = "bg", bold = true })
	hl(0, "Todo", { fg = c.purple, bg = bg, bold = true })
	hl(0, "Type", { fg = c.blue })
	hl(0, "Typedef", { fg = c.blue })
	hl(0, "Underlined", { fg = "fg", bg = "bg", underline = true })
	hl(0, "Variable", { fg = c.light_blue })
	hl(0, "VertSplit", { fg = c.bg, bg = fg })
	hl(0, "Visual", { fg = "fg", bg = ui_blue })
	hl(0, "VisualNOS", { fg = "fg", bg = alt_bg })
	hl(0, "WarningMsg", { fg = c.error_red, bg = bg })
	hl(0, "Whitespace", { fg = c.bg, bg = "bg" })
	hl(0, "WildMenu", { fg = c.alt_bg, bg = blue })
	hl(0, "lCursor", { fg = c.cursor_fg, bg = cursor_bg })

	-- lsp
	hl(0, "LspDiagnosticsDefaultError", { fg = c.error_red })
	hl(0, "LspDiagnosticsDefaultHint", { fg = c.hint_blue })
	hl(0, "LspDiagnosticsDefaultInformation", { fg = c.info_yellow })
	hl(0, "LspDiagnosticsDefaultWarning", { fg = c.warning_orange })
	hl(0, "LspDiagnosticsError", { fg = c.error_red })
	hl(0, "LspDiagnosticsFloatingError", { fg = c.error_red })
	hl(0, "LspDiagnosticsFloatingHint", { fg = c.hint_blue })
	hl(0, "LspDiagnosticsFloatingInformation", { fg = c.info_yellow })
	hl(0, "LspDiagnosticsFloatingWarning", { fg = c.warning_orange })
	hl(0, "LspDiagnosticsHint", { fg = c.hint_blue })
	hl(0, "LspDiagnosticsInformation", { fg = c.info_yellow })
	hl(0, "LspDiagnosticsSignError", { fg = c.error_red })
	hl(0, "LspDiagnosticsSignHint", { fg = c.hint_blue })
	hl(0, "LspDiagnosticsSignInformation", { fg = c.info_yellow })
	hl(0, "LspDiagnosticsSignWarning", { fg = c.warning_orange })
	hl(0, "LspDiagnosticsUnderlineError", { fg = "fg", bg = "bg", underline = true })
	hl(0, "LspDiagnosticsUnderlineHint", { fg = "fg", bg = "bg", underline = true })
	hl(0, "LspDiagnosticsUnderlineInformation", { fg = "fg", bg = "bg", underline = true })
	hl(0, "LspDiagnosticsUnderlineWarning", { fg = "fg", bg = "bg", underline = true })
	hl(0, "LspDiagnosticsVirtualTextError", { fg = c.error_red })
	hl(0, "LspDiagnosticsVirtualTextHint", { fg = c.hint_blue })
	hl(0, "LspDiagnosticsVirtualTextInformation", { fg = c.info_yellow })
	hl(0, "LspDiagnosticsVirtualTextWarning", { fg = c.warning_orange })
	hl(0, "LspDiagnosticsWarning", { fg = c.warning_orange })
	hl(0, "QuickScopePrimary", { fg = c.purple_test, bg = "bg", underline = true })
	hl(0, "QuickScopeSecondary", { fg = c.cyan_test, bg = "bg", underline = true })

	-- markdown
	hl(0, "markdownBlockquote", { fg = c.accent })
	hl(0, "markdownBold", { fg = c.yellow, bg = "bg", bold = true })
	hl(0, "markdownCode", { fg = c.green })
	hl(0, "markdownCodeBlock", { fg = c.green })
	hl(0, "markdownCodeDelimiter", { fg = c.green })
	hl(0, "markdownH1", { fg = c.blue })
	hl(0, "markdownH2", { fg = c.blue })
	hl(0, "markdownH3", { fg = c.blue })
	hl(0, "markdownH4", { fg = c.blue })
	hl(0, "markdownH5", { fg = c.blue })
	hl(0, "markdownH6", { fg = c.blue })
	hl(0, "markdownHeadingDelimiter", { fg = c.red })
	hl(0, "markdownHeadingRule", { fg = c.accent })
	hl(0, "markdownId", { fg = c.purple })
	hl(0, "markdownIdDeclaration", { fg = c.blue })
	hl(0, "markdownIdDelimiter", { fg = c.light_gray })
	hl(0, "markdownItalic", { fg = "fg", bg = "bg", italic = true })
	hl(0, "markdownLinkDelimiter", { fg = c.light_gray })
	hl(0, "markdownLinkText", { fg = c.blue })
	hl(0, "markdownListMarker", { fg = c.red })
	hl(0, "markdownOrderedListMarker", { fg = c.red })
	hl(0, "markdownRule", { fg = c.accent })
	hl(0, "markdownUrl", { fg = c.cyan, bg = "bg", underline = true })

	-- misc
	hl(0, "CompeDocumentation", { fg = "fg", bg = alt_bg })
	hl(0, "debugBreakpoint", { fg = c.red, bg = "bg" })
	hl(0, "debugPc", { fg = "fg", bg = cyan })
	hl(0, "xmlEndTag", { fg = c.cyan })
	hl(0, "xmlTag", { fg = c.cyan })
	hl(0, "xmlTagName", { fg = c.cyan })

	-- nvim_tree
	hl(0, "NvimTreeExecFile", { fg = c.green })
	hl(0, "NvimTreeFolderIcon", { fg = c.blue })
	hl(0, "NvimTreeFolderName", { fg = c.blue })
	hl(0, "NvimTreeGitDeleted", { fg = c.sign_delete })
	hl(0, "NvimTreeGitDirty", { fg = c.sign_add })
	hl(0, "NvimTreeGitMerge", { fg = c.sign_change })
	hl(0, "NvimTreeGitNew", { fg = c.sign_add })
	hl(0, "NvimTreeGitRenamed", { fg = c.sign_change })
	hl(0, "NvimTreeGitStaged", { fg = c.sign_add })
	hl(0, "NvimTreeImageFile", { fg = c.purple })
	hl(0, "NvimTreeIndentMarker", { fg = c.gray })
	hl(0, "NvimTreeNormal", { fg = c.light_gray, bg = alt_bg })
	hl(0, "NvimTreeOpenedFolderName", { fg = c.cyan, bg = "bg", italic = true })
	hl(0, "NvimTreeRootFolder", { fg = c.fg, bg = "bg", bold = true })
	hl(0, "NvimTreeSpecialFile", { fg = c.orange })
	hl(0, "NvimTreeSymlink", { fg = c.cyan })
	hl(0, "NvimTreeVertSplit", { fg = c.alt_bg, bg = alt_bg })

	-- telescope
	hl(0, "TelescopeBorder", { fg = c.fg, bg = bg })
	hl(0, "TelescopeMatching", { fg = c.info_yellow, bg = "bg", bold = true })
	hl(0, "TelescopeSelection", { fg = c.hint_blue })

	-- treesitter
	hl(0, "TSAnnotation", { fg = c.yellow })
	hl(0, "TSAttribute", { fg = c.orange })
	hl(0, "TSBoolean", { fg = c.blue })
	hl(0, "TSCharacter", { fg = c.orange })
	hl(0, "TSComment", { fg = c.comment })
	hl(0, "TSConditional", { fg = c.blue })
	hl(0, "TSConstBuiltin", { fg = c.blue })
	hl(0, "TSConstMacro", { fg = c.orange })
	hl(0, "TSConstant", { fg = c.yellow })
	hl(0, "TSConstructor", { fg = c.orange })
	hl(0, "TSEmphasis", { fg = "fg", bg = "bg", italic = true })
	hl(0, "TSError", { fg = c.error_red })
	hl(0, "TSException", { fg = c.purple })
	hl(0, "TSField", { fg = c.light_blue })
	hl(0, "TSFloat", { fg = c.green })
	hl(0, "TSFuncBuiltin", { fg = c.yellow })
	hl(0, "TSFuncMacro", { fg = c.yellow })
	hl(0, "TSFunction", { fg = c.yellow })
	hl(0, "TSInclude", { fg = c.purple })
	hl(0, "TSKeyword", { fg = c.blue })
	hl(0, "TSKeywordFunction", { fg = c.blue })
	hl(0, "TSKeywordOperator", { fg = c.blue })
	hl(0, "TSKeywordReturn", { fg = c.purple })
	hl(0, "TSLabel", { fg = c.light_blue })
	hl(0, "TSLiteral", { fg = c.yellow_orange })
	hl(0, "TSMethod", { fg = c.yellow })
	hl(0, "TSNamespace", { fg = c.orange })
	hl(0, "TSNumber", { fg = c.green })
	hl(0, "TSOperator", { fg = c.fg })
	hl(0, "TSParameter", { fg = c.light_blue })
	hl(0, "TSParameterReference", { fg = c.light_blue })
	hl(0, "TSProperty", { fg = c.light_blue })
	hl(0, "TSPunctBracket", { fg = c.fg, bg = "bg" })
	hl(0, "TSPunctDelimiter", { fg = c.fg, bg = "bg" })
	hl(0, "TSPunctSpecial", { fg = c.fg })
	hl(0, "TSQueryLinterError", { fg = c.warning_orange })
	hl(0, "TSRepeat", { fg = c.purple })
	hl(0, "TSString", { fg = c.cyan })
	hl(0, "TSStringEscape", { fg = c.green })
	hl(0, "TSStringRegex", { fg = c.cyan })
	hl(0, "TSStrong", { fg = c.yellow_orange })
	hl(0, "TSStructure", { fg = c.light_blue })
	hl(0, "TSSymbol", { fg = c.light_blue })
	hl(0, "TSTag", { fg = c.blue })
	hl(0, "TSTagDelimiter", { fg = c.gray })
	hl(0, "TSText", { fg = c.fg })
	hl(0, "TSTitle", { fg = c.blue, bg = "bg", bold = true })
	hl(0, "TSType", { fg = c.orange })
	hl(0, "TSTypeBuiltin", { fg = c.blue })
	hl(0, "TSURI", { fg = c.yellow_orange, bg = "bg", underline = true })
	hl(0, "TSUnderline", { fg = "fg", bg = "bg", underline = true })
	hl(0, "TSVariable", { fg = c.light_blue })
	hl(0, "TSVariableBuiltin", { fg = c.light_blue })

	-- whichkey
	hl(0, "WhichKey", { fg = c.purple })
	hl(0, "WhichKeyDesc", { fg = c.light_blue })
	hl(0, "WhichKeyFloat", { fg = "fg", bg = dark })
	hl(0, "WhichKeyGroup", { fg = c.blue })
	hl(0, "WhichKeySeperator", { fg = c.green })

end

return M
